<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$customerObj = $objectManager->create('\Magento\Customer\Model\Session');
	$fileSystem = $objectManager->create('\Magento\Framework\Filesystem');
	$mediaPath = $fileSystem->getDirectoryRead(\Magento\Framework\App\Filesystem\DirectoryList::MEDIA)->getAbsolutePath();
	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$baseUrl = $storeManager->getStore()->getBaseUrl();
	$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
	
	$productId = 1;
	if(isset($_GET['product_id'])){
		$productId = $_GET['product_id'];
	}
// 	$fonts = $this->getFonts();

	$fonts = $objectManager->create('Laurensmedia\Productdesigner\Model\ResourceModel\Fonts\Collection')
		->setOrder('name','ASC');

	$productFonts = $objectManager->create('Laurensmedia\Productdesigner\Model\ResourceModel\Productfonts\Collection')
		->addFieldToFilter('product_id', $productId)
		->getFirstItem()
		->getFonts();
		
	$productFonts = explode(',', $productFonts);
	if(count($productFonts) > 0 && ($productFonts[0] != '' || isset($productFonts[1]))){
		$fonts = $objectManager->create('Laurensmedia\Productdesigner\Model\ResourceModel\Fonts\Collection')
			->setOrder('name','ASC')
			->addFieldToFilter('id_fonts', $productFonts);
	}
	$storeId = $storeManager->getStore()->getStoreId();

	$finalFonts = array();
	foreach($fonts as $font) {
		$fontLabel = $font['fontlabel'];
		$fontName = strtolower($font['name']);
		$path = $mediaPath .'productdesigner_fonts/';
		$translationFile = $path.$font['fontfamily'].'.php';

		$fontName = $font['name'];
		if(file_exists($translationFile)) {
			$translation = json_decode(file_get_contents($translationFile), true);
			if(isset($translation[$storeId])){
				$fontName = $translation[$storeId];
			}
		}
		$font['name'] = $fontName;
		$finalFonts[$fontName] = $font;
	}

	ksort($finalFonts);

?>

<div class="pd-text-editor">
	<span class="pd-text-title"><?php echo __('Tekst invoegen'); ?></span>
    <div class="pd-row">
	<span><?php echo __('Selecteer uw lettertype:'); ?><br/></span>
	<select id="pd-fonts-chooser">
		<?php foreach($finalFonts as $font) { ?>
			<option value="<?php echo $font['fontfamily']; ?>"><?php echo $font['name']; ?></option>
		<?php } ?>
	</select>

    </div>
    <div class="pd-row">
	<textarea id="pd-user-text" rows="4" cols="25" data-label="<?php echo __('Vul hier uw tekst in'); ?>"></textarea>
	</div>
    <div class="pd-row">
	<p><label><?php echo __('Kies tekst kleur:');?> </label><input class='add_text_color' value="" /></p>
    </div>
	<button id="pd-add-text"><?php echo __('Plaats tekst') ?></button>
</div>
<style type="text/css">
	.simpleColorCancelButton,
	.simpleColorSelectButton {
		display: none !important;
	}
</style>
<script>
require(['jquery'], function($){
	jQuery("#pd-user-text").focus(function()
	{
		if (jQuery(this).val() == jQuery(this).data("label"))
			jQuery(this).val("");
	});
	jQuery("#pd-user-text").blur(function()
	{
		if (jQuery(this).val() == "")
			jQuery(this).val(jQuery(this).data("label"));
	});

	if (jQuery("#pd-user-text").val() == "")
		jQuery("#pd-user-text").val(jQuery("#pd-user-text").data("label"));

	jQuery(".leftnav-3 .pd-leftnav").click(function()
	{
		jQuery(".simpleColorSelectButton").trigger('click');
		jQuery(".simpleColorCancelButton").hide();
	});
});
</script>
