<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$customerObj = $objectManager->create('\Magento\Customer\Model\Session');
	$fileSystem = $objectManager->create('\Magento\Framework\Filesystem');
	$mediaPath = $fileSystem->getDirectoryRead(\Magento\Framework\App\Filesystem\DirectoryList::MEDIA)->getAbsolutePath();
	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$baseUrl = $storeManager->getStore()->getBaseUrl();
	$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
    $registry = $objectManager->get('Magento\Framework\Registry');
    $product = $registry->registry('current_product');
?>
<span class="pd-text-title" style="margin-bottom: 0; font-weight: bold;"><?php echo __('Afbeelding invoegen'); ?></span>

<?php if($product->getData('enable_designer_images') == '1'): ?>
	<span style="font-size: 12px; text-decoration: underline; color: red; margin-bottom: 15px; display: block;"><?php echo __('Wilt u de kleur zwart veranderen?<br />
	Klik dan na uw keuze op het kleurenvakje rechtsboven en pas uw kleur aan.'); ?></span>
	<?php
		$cats = $objectManager->create('Laurensmedia\Productdesigner\Model\ResourceModel\Imagecategories\Collection')
			->addFieldToFilter('stores', array('finset' => $storeManager->getStore()->getStoreId()))
			->getData();
	?>
	<div class="pd-row">
	<?php echo __('Afbeeldingen'); ?>
	<div class="pd-library-select-category">
		<select id="select_library">
		<option value=""><?php echo __('-- Categorie --') ?></option>
		<?php
		//$cats = $this->getImgCat();
			if(sizeof($cats) > 0) {
				foreach($cats as $cat) {
					if($cat['is_background'] == 0){
				?>
						<option value="<?php echo $cat['id'] ?>"><?php echo __($cat['label']); ?></option>
				<?php
					}
				}
			}
			?>
		</select>
	</div>
	
	</div>
	<div class="pd-row">
	
	<!-- Image category loader -->
	<div class="pd-loading-library-category" style="display: none;">
		<div class="loading-mask-loader">
			<img src="<?php echo $this->getViewFileUrl('Laurensmedia_Productdesigner::images/productdesigner/ajaxload.gif'); ?>" width="30px" alt="<?php echo __('Loading...') ?>"/>
		</div>
	</div>
	
	</div>
	<div class="pd-row">
	
	<!--- Container for images -->
	<div class="pd-library-images"></div>
	<?php /*
	Achtergronden
	<div class="pd-library-select-category-background">
		<select id="select_library_background">
		<option value=""><?php echo __('-- Please Select --') ?></option>
		<?php
		$cats = $this->getImgCat();
			if(sizeof($cats) > 0) {
				foreach($cats as $cat) {
					if($cat['is_background'] == 1){
				?>
						<option value="<?php echo $cat['id'] ?>"><?php echo $cat['label']; ?></option>
				<?php
					}
				}
			}
			?>
	
		</select>
	</div>
	*/?>
	</div>
	<div class="pd-row">
	
	<!-- Background image category loader -->
	<div class="pd-loading-library-background-category" style="display: none;">
		<div class="loading-mask-loader">
			<img src="<?php echo $this->getViewFileUrl('Laurensmedia_Productdesigner::images/productdesigner/ajaxload.gif'); ?>" width="30px" alt="<?php echo __('Loading...') ?>"/>
		</div>
	</div>
	</div>
	
	<div class="pd-row">
	
	<!--- Container for background images -->
	<div class="pd-library-background-images"></div>
	
	</div>
	
	<!--
	<div class="pd-row">
		<p><label><?php echo __('Kies afbeelding kleur:');?> </label><input class='add_image_color' value="" /></p>
	</div>
	<div class="pd-row">
		<br />
		<button id="pd-add-image"><?php echo __('Plaats afbeelding') ?></button>
	</div>
	-->
<?php endif; ?>


<?php if($product->getData('enable_designer_upload') == '1'): ?>
	<div id="file-upload">
		<form id="file_upload_form" method="post" enctype="multipart/form-data" action="<?php echo $this->getUrl('productdesigner/index/upload'); ?>">
			<?php echo __('Uw afbeelding (.jpg/.png)') ?><br>
			<input name="file" id="file" size="20" type="file" class="fileupl">
		</form>
	</div>
	<div style="width:200px;height:15px;border:1px solid #fff;margin:0;padding:0;margin-top:10px;display:none;">
		<div id="uploadprogress" style="float:left;height:15px;background:#ff9c00;">
			<p style="color:#fff;font-size:10pt;" id="uploadprogresstext"></p>
		</div>
	</div>
<?php endif; ?>