<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$customerObj = $objectManager->create('\Magento\Customer\Model\Session');
	$fileSystem = $objectManager->create('\Magento\Framework\Filesystem');
	$mediaPath = $fileSystem->getDirectoryRead(\Magento\Framework\App\Filesystem\DirectoryList::MEDIA)->getAbsolutePath();
	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$baseUrl = $storeManager->getStore()->getBaseUrl();
	$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
	
	$productId = 1;
	if(isset($_GET['product_id'])){
		$productId = $_GET['product_id'];
	}
// 	$fonts = $this->getFonts();

	$fonts = $objectManager->create('Laurensmedia\Productdesigner\Model\ResourceModel\Fonts\Collection')
		->setOrder('name','ASC');

	$productFonts = $objectManager->create('Laurensmedia\Productdesigner\Model\ResourceModel\Productfonts\Collection')
		->addFieldToFilter('product_id', $productId)
		->getFirstItem()
		->getFonts();
	$productFonts = explode(',', $productFonts);
	if(count($productFonts) > 0 && ($productFonts[0] != '' || isset($productFonts[1]))){
		$fonts = $objectManager->create('Laurensmedia\Productdesigner\Model\ResourceModel\Fonts\Collection')
			->setOrder('name','ASC')
			->addFieldToFilter('id_fonts', $productFonts);
	}
	$storeId = $storeManager->getStore()->getStoreId();

	$finalFonts = array();
	foreach($fonts as $font) {
		$fontLabel = $font['fontlabel'];
		$fontName = strtolower($font['name']);
		$path = $mediaPath .'productdesigner_fonts/';
		$translationFile = $path.$font['fontfamily'].'.php';
		$fontName = $font['name'];

		if(file_exists($translationFile)) {
			$translation = json_decode(file_get_contents($translationFile), true);
			if(isset($translation[$storeId])){
				$fontName = $translation[$storeId];
			}
		}
		$font['name'] = $fontName;
		$finalFonts[$fontName] = $font;
	}

	ksort($finalFonts);
?>

<span class="pd-toolbox-item">
	<label><?php echo __('Font:') ?> </label>
	<select id="pd-tools-font">
		<?php foreach($finalFonts as $font) { ?>
			<option value="<?php echo $font['fontfamily']; ?>"><?php echo $font['name']; ?></option>
		<?php } ?>
	</select>
</span>
