<input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>" />
<input type="hidden" name="id" value="<?php echo $block->getProductId() ?>" />
<input type="hidden" name="product_id" value="<?php echo $block->getProductId() ?>" />
<input type="hidden" name="store_switch" value="<?php echo $block->getStoreId() ?>" />

<button id="savedesigner" type="submit" class="scalable primary" style="position: fixed; top: 100px; right: 15px; z-index: 9999;"><span>Save designer</span></button>