<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$stores = $storeManager->getStores();
$types = array('engraving', 'sublimation', 'printing', 'wood');

$itemsToProcess = $objectManager->create('Laurensmedia\Productdesigner\Model\ResourceModel\Bulkexport\Collection')
	->addFieldToFilter('finished', array('neq' => '1'));
$typesToProcess = array();
foreach($itemsToProcess as $item){
	$itemId = $item->getId();
	$orderItem = $objectManager->create('Magento\Sales\Model\Order\Item')->load($item->getOrderItemId());
	foreach($types as $type){
		$product = $orderItem->getProduct();
		$productPrintingTypes = explode(',', str_replace(' ', '', $product->getResource()->getAttribute('technology')->getFrontend()->getValue($product)));
		if(in_array($type, $productPrintingTypes)){
			$typesToProcess[] = 'store-'.$orderItem->getStoreId().'-type-'.$type;
		}
	}
}
$typesToProcess = array_unique(array_filter($typesToProcess));
?>
<table class="data-grid">
	<tbody>
		<tr>
			<td></td>
			<?php foreach($stores as $store): ?>
				<td class="store-<?php echo $store->getStoreId(); ?>"><?php echo $store->getName(); ?></td>
			<?php endforeach; ?>
		</tr>
		<?php foreach($types as $type): ?>
			<tr class="type-<?php echo $type; ?>">
				<td><?php echo $type; ?></td>
				<?php foreach($stores as $store): ?>
					<td class="download-cell store-<?php echo $store->getStoreId(); ?>-type-<?php echo $type; ?>">
						<span class="processing-cell">
							<?php if(in_array('store-'.$store->getStoreId().'-type-'.$type, $typesToProcess)): ?>
								Processing...
							<?php endif; ?>
						</span>
						<a href="<?php echo $this->getUrl('productdesigner/bulkexport/downloadzip/').'?store='.$store->getStoreId().'&type='.$type; ?>" target="_blank" class="action-default primary add download-link" style="display:none;"><span>Download</span></a>
					</td>
				<?php endforeach; ?>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<?php echo $block->getGridHtml() ?>
<script type="text/javascript">
	var processedIds = [];
	require(['jquery'], function($){
		var jobUrl = '<?php echo $this->getUrl('productdesigner/bulkexport/runqueue');?>';
		var updatesUrl = '<?php echo $this->getUrl('productdesigner/bulkexport/checkupdates');?>';
		jQuery.ajax({
			type: "POST",
			url: jobUrl,
			data: {
				form_key: window.FORM_KEY
			}
		});
		setInterval(function(){
			jQuery.ajax({
				type: "POST",
				url: updatesUrl,
				dataType: "json",
				data: {
					form_key: window.FORM_KEY
				},
				success: function(result){
					var processNextJob = false;
					jQuery.each(result.items, function(id, data){
						var itemHtml = '<p>Yes</p>';
						if(data.pdf_file_printing != null){
							itemHtml += '<a href="'+data.base_url+data.pdf_file_printing+'" target="_blank">Printing</a><br />';
						}
						if(data.pdf_file_sublimation != null){
							itemHtml += '<a href="'+data.base_url+data.pdf_file_sublimation+'" target="_blank">Sublimation</a><br />';
						}
						if(data.pdf_file_engraving != null){
							itemHtml += '<a href="'+data.base_url+data.pdf_file_engraving+'" target="_blank">Engraving</a><br />';
						}
						if(data.pdf_file_wood != null){
							itemHtml += '<a href="'+data.base_url+data.pdf_file_wood+'" target="_blank">Wood</a><br />';
						}
						jQuery(".data-grid tbody tr:visible").each(function(index, row){
							if($(row).find('td').first().text().trim() == id){
								$(row).find('td.col-finished').html(itemHtml);
							}
						});
						if(jQuery.inArray(id, processedIds) == -1){
							processNextJob = true;
							processedIds.push(id);
						}
					});
					jQuery.each(result.downloads, function(index, className){
						jQuery(".download-cell."+className+" .download-link").show();
						jQuery(".download-cell."+className+" .processing-cell").hide();
					});
					jQuery.each(result.processing, function(id, className){
						jQuery(".download-cell."+className+" .download-link").hide();
						jQuery(".download-cell."+className+" .processing-cell").show();
					});
					if(processNextJob == true){
						// Start processing next job
						jQuery.ajax({
							type: "POST",
							url: jobUrl,
							data: {
								form_key: window.FORM_KEY
							}
						});
					}
				}
			});
		}, 5000);
	});
</script>
<style type="text/css">
#postGrid{
	display: none;
}
</style>